from tkinter import*
import tkinter as tk
from tkinter import ttk
from Clase import *
ventana = Tk()
ventana.title("Examen2doP")
seccion1=Frame(ventana,bg="green")
seccion1.pack(expand=True,fill='both')
Nom = Label(seccion1, text="Ingrese su nombre:", bg="green")
Nom.pack()
Nombre = ttk.Entry(seccion1)
Nombre.pack()
ap = Label(seccion1, text="Ingrese su apellido paterno:", bg="green")
ap.pack()
AP = ttk.Entry(seccion1)
AP.pack()
am = Label(seccion1, text="Ingrese su nombre:", bg="green")
am.pack()
AM = ttk.Entry(seccion1)
AM.pack()
nac = Label(seccion1, text="Ingrese su año de nacimiento:", bg="green")
nac.pack()
NAC = ttk.Entry(seccion1)
NAC.pack()
carr = Label(seccion1, text="Ingrese su carrera:", bg="green")
carr.pack()
Carr = ttk.Entry(seccion1)
Carr.pack()
matricula = MATRICULA(Nombre,AP,AM,NAC,Carr)
Continuar = Button(seccion1,text="Continuar",bg="black",fg="white",command=matricula.Matricula)
Continuar.pack()
ventana.mainloop()